export const productsMock = [
  {
    id: "1",
    productImage: "/Coffee-1.png",
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.9,
    labels: ["Tradicional"],
  },
  {
    id: "2",
    productImage: "/Coffee-2.png",
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 9.9,
    labels: ["Tradicional", "Com Leite"],
  },
  {
    id: "3",
    productImage: "/Coffee-3.png",
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.9,
    labels: ["Tradicional", "Com Leite"],
  },
  {
    id: "4",
    productImage: "/Coffee-4.png",
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.9,
    labels: ["Especial"],
  },
  {
    id: "5",
    productImage: "/Coffee-5.png",
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 9.9,
    labels: ["Tradicional"],
  },
  {
    id: "6",
    productImage: "/Coffee-6.png",
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 9.9,
    labels: ["Tradicional"],
  },
];
